In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('solar.csv')

In [3]:
data.head()

,Day of Year,Year,Month,Day,First Hour of Period,Is Daylight,Distance to Solar Noon,Average Temperature (Day),Average Wind Direction (Day),Average Wind Speed (Day),Sky Cover,Visibility,Relative Humidity,Average Wind Speed (Period),Average Barometric Pressure (Period),Power Generated
0,245,2008,9,1,1,False,0.859897,69,28,7.5,0,10.0,75,8.0,29.82,0
1,245,2008,9,1,4,False,0.628535,69,28,7.5,0,10.0,77,5.0,29.85,0
2,245,2008,9,1,7,True,0.397172,69,28,7.5,0,10.0,70,0.0,29.89,5418
3,245,2008,9,1,10,True,0.165810,69,28,7.5,0,10.0,33,0.0,29.91,25477
4,245,2008,9,1,13,True,0.065553,69,28,7.5,0,10.0,21,3.0,29.89,30069

In [4]:
data.shape

(2920, 16)

In [5]:
data.isnull().sum()

Day of Year                             0
Year                                    0
Month                                   0
Day                                     0
First Hour of Period                    0
Is Daylight                             0
Distance to Solar Noon                  0
Average Temperature (Day)               0
Average Wind Direction (Day)            0
Average Wind Speed (Day)                0
Sky Cover                               0
Visibility                              0
Relative Humidity                       0
Average Wind Speed (Period)             1
Average Barometric Pressure (Period)    0
Power Generated                         0
dtype: int64

In [6]:
df = data.dropna()

In [7]:
df.head()

,Day of Year,Year,Month,Day,First Hour of Period,Is Daylight,Distance to Solar Noon,Average Temperature (Day),Average Wind Direction (Day),Average Wind Speed (Day),Sky Cover,Visibility,Relative Humidity,Average Wind Speed (Period),Average Barometric Pressure (Period),Power Generated
0,245,2008,9,1,1,False,0.859897,69,28,7.5,0,10.0,75,8.0,29.82,0
1,245,2008,9,1,4,False,0.628535,69,28,7.5,0,10.0,77,5.0,29.85,0
2,245,2008,9,1,7,True,0.397172,69,28,7.5,0,10.0,70,0.0,29.89,5418
3,245,2008,9,1,10,True,0.165810,69,28,7.5,0,10.0,33,0.0,29.91,25477
4,245,2008,9,1,13,True,0.065553,69,28,7.5,0,10.0,21,3.0,29.89,30069

In [8]:
df.shape

(2919, 16)

In [9]:
df.columns

Index(['Day of Year', 'Year', 'Month', 'Day', 'First Hour of Period',
       'Is Daylight', 'Distance to Solar Noon', 'Average Temperature (Day)',
       'Average Wind Direction (Day)', 'Average Wind Speed (Day)', 'Sky Cover',
       'Visibility', 'Relative Humidity', 'Average Wind Speed (Period)',
       'Average Barometric Pressure (Period)', 'Power Generated'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 2919
Data columns (total 16 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Day of Year                           2919 non-null   int64
 1   Year                                  2919 non-null   int64
 2   Month                                 2919 non-null   int64
 3   Day                                   2919 non-null   int64
 4   First Hour of Period                  2919 non-null   int64
 5   Is Daylight                           2919 non-null   bool
 6   Distance to Solar Noon                2919 non-null   float64
 7   Average Temperature (Day)             2919 non-null   int64
 8   Average Wind Direction (Day)          2919 non-null   int64
 9   Average Wind Speed (Day)              2919 non-null   float64
 10  Sky Cover                             2919 non-null   int64
 11  Visibility                            2919 non-null   float64
 12  Relative Humidity                     2919 non-null   int64
 13  Average Wind Speed (Period)           2919 non-null   float64
 14  Average Barometric Pressure (Period)  2919 non-null   float64
 15  Power Generated                       2919 non-null   int64
dtypes: bool(1), float64(5), int64(10)
memory usage: 367.7 KB

In [11]:
df.describe()

,Day of Year,Year,Month,Day,First Hour of Period,Distance to Solar Noon,Average Temperature (Day),Average Wind Direction (Day),Average Wind Speed (Day),Sky Cover,Visibility,Relative Humidity,Average Wind Speed (Period),Average Barometric Pressure (Period),Power Generated
count,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000
mean,183.282631,2008.665982,6.524495,15.715999,11.501542,0.503327,58.468996,24.957862,10.099486,1.987667,9.559609,73.505995,10.129154,30.017712,6982.182939
std,105.751253,0.471727,3.448038,8.795825,6.875714,0.298069,6.842318,6.912203,4.837128,1.412220,1.380290,15.073974,7.261547,0.142006,10313.330078
min,1.000000,2008.000000,1.000000,1.000000,1.000000,0.050401,42.000000,1.000000,1.100000,0.000000,0.000000,14.000000,0.000000,29.480000,0.000000
25%,92.000000,2008.000000,4.000000,8.000000,5.500000,0.232061,53.000000,25.000000,6.600000,1.000000,10.000000,65.000000,5.000000,29.920000,0.000000
50%,183.000000,2009.000000,7.000000,16.000000,13.000000,0.479241,59.000000,27.000000,10.000000,2.000000,10.000000,77.000000,9.000000,30.000000,404.000000
75%,275.000000,2009.000000,10.000000,23.000000,17.500000,0.739559,63.000000,29.000000,13.100000,3.000000,10.000000,84.000000,15.000000,30.110000,12725.000000
max,366.000000,2009.000000,12.000000,31.000000,22.000000,1.141361,78.000000,36.000000,26.600000,4.000000,10.000000,100.000000,40.000000,30.530000,36580.000000

In [12]:
df.isnull().sum()

Day of Year                             0
Year                                    0
Month                                   0
Day                                     0
First Hour of Period                    0
Is Daylight                             0
Distance to Solar Noon                  0
Average Temperature (Day)               0
Average Wind Direction (Day)            0
Average Wind Speed (Day)                0
Sky Cover                               0
Visibility                              0
Relative Humidity                       0
Average Wind Speed (Period)             0
Average Barometric Pressure (Period)    0
Power Generated                         0
dtype: int64

In [13]:
df.isna().sum()

Day of Year                             0
Year                                    0
Month                                   0
Day                                     0
First Hour of Period                    0
Is Daylight                             0
Distance to Solar Noon                  0
Average Temperature (Day)               0
Average Wind Direction (Day)            0
Average Wind Speed (Day)                0
Sky Cover                               0
Visibility                              0
Relative Humidity                       0
Average Wind Speed (Period)             0
Average Barometric Pressure (Period)    0
Power Generated                         0
dtype: int64

In [14]:
df = df.rename(columns={'Day of Year':'Day_of_Year','Is Daylight':'Is_Daylight','First Hour of Period':'First_Hour_of_Period','Is Daylight':'Is_Daylight','Distance to Solar Noon':'Distance_to_Solar_Noon','Average Temperature (Day)':'Average_Temperature','Average Wind Direction (Day)':'Average_Wind_Direction','Average Wind Speed (Day)':'Average_Wind_Speed','Sky Cover':'Sky_Cover','Relative Humidity':'Relative_Humidity','Average Wind Speed (Period)':'Average_Wind_Speed','Average Barometric Pressure (Period)':'Average_Barometric_Pressure','Power Generated':'Power_Generated'})

In [15]:
df.columns

Index(['Day_of_Year', 'Year', 'Month', 'Day', 'First_Hour_of_Period',
       'Is_Daylight', 'Distance_to_Solar_Noon', 'Average_Temperature',
       'Average_Wind_Direction', 'Average_Wind_Speed', 'Sky_Cover',
       'Visibility', 'Relative_Humidity', 'Average_Wind_Speed',
       'Average_Barometric_Pressure', 'Power_Generated'],
      dtype='object')

In [16]:
df.First_Hour_of_Period.unique()

array([ 1,  4,  7, 10, 13, 16, 19, 22], dtype=int64)

In [17]:
df.Is_Daylight.unique()

array([False,  True])

In [18]:
df.Distance_to_Solar_Noon.unique()

array([0.85989717, 0.6285347 , 0.39717224, ..., 0.29449424, 0.52496799,
       0.75544174])

In [19]:
df.corr()

,Day_of_Year,Year,Month,Day,First_Hour_of_Period,Is_Daylight,Distance_to_Solar_Noon,Average_Temperature,Average_Wind_Direction,Average_Wind_Speed,Sky_Cover,Visibility,Relative_Humidity,Average_Wind_Speed,Average_Barometric_Pressure,Power_Generated
Day_of_Year,1.000000,-0.818412,0.996520,0.094129,0.000320,-0.055288,0.044453,0.257789,0.192094,-0.088287,-0.052670,-0.004226,0.031508,-0.073227,-0.122886,-0.037070
Year,-0.818412,1.000000,-0.818255,-0.001974,-0.000317,0.087559,-0.135724,-0.046688,0.005246,0.304131,0.092584,0.089275,-0.003405,0.214389,-0.069480,0.122813
Month,0.996520,-0.818255,1.000000,0.011230,0.000291,-0.055260,0.043132,0.263076,0.186718,-0.081456,-0.048429,-0.004915,0.028697,-0.068733,-0.128667,-0.036304
Day,0.094129,-0.001974,0.011230,1.000000,0.000339,0.004517,-0.000434,-0.021992,0.111685,-0.035234,-0.050991,0.027752,0.031739,-0.023474,0.037990,0.007063
First_Hour_of_Period,0.000320,-0.000317,0.000291,0.000339,1.000000,0.173255,-0.062237,-0.000048,-0.000420,-0.000338,-0.073585,0.049903,-0.251581,0.289482,-0.033481,0.107209
Is_Daylight,-0.055288,0.087559,-0.055260,0.004517,0.173255,1.000000,-0.827087,0.067295,0.056829,0.060376,0.028588,-0.086235,-0.341510,0.192290,-0.054039,0.532336
Distance_to_Solar_Noon,0.044453,-0.135724,0.043132,-0.000434,-0.062237,-0.827087,1.000000,-0.145235,-0.118293,-0.145301,-0.015183,0.065541,0.369278,-0.214891,0.082633,-0.746825
Average_Temperature,0.257789,-0.046688,0.263076,-0.021992,-0.000048,0.067295,-0.145235,1.000000,0.342216,0.096194,-0.230673,0.194354,-0.221440,0.054546,-0.435728,0.132155
Average_Wind_Direction,0.192094,0.005246,0.186718,0.111685,-0.000420,0.056829,-0.118293,0.342216,1.000000,0.340899,-0.137217,0.201546,-0.095053,0.229844,-0.271973,0.146463
Average_Wind_Speed,-0.088287,0.304131,-0.081456,-0.035234,-0.000338,0.060376,-0.145301,0.096194,0.340899,1.000000,0.107840,0.183281,0.005676,0.673626,-0.379447,0.142366
Sky_Cover,-0.052670,0.092584,-0.048429,-0.050991,-0.073585,0.028588,-0.015183,-0.230673,-0.137217,0.107840,1.000000,-0.224131,0.394722,0.044301,-0.091531,-0.187248
Visibility,-0.004226,0.089275,-0.004915,0.027752,0.049903,-0.086235,0.065541,0.194354,0.201546,0.183281,-0.224131,1.000000,-0.290180,0.143621,-0.104273,0.075841
Relative_Humidity,0.031508,-0.003405,0.028697,0.031739,-0.251581,-0.341510,0.369278,-0.221440,-0.095053,0.005676,0.394722,-0.290180,1.000000,-0.218042,0.017987,-0.522445
Average_Wind_Speed,-0.073227,0.214389,-0.068733,-0.023474,0.289482,0.192290,-0.214891,0.054546,0.229844,0.673626,0.044301,0.143621,-0.218042,1.000000,-0.293457,0.278174
Average_Barometric_Pressure,-0.122886,-0.069480,-0.128667,0.037990,-0.033481,-0.054039,0.082633,-0.435728,-0.271973,-0.379447,-0.091531,-0.104273,0.017987,-0.293457,1.000000,-0.036553
Power_Generated,-0.037070,0.122813,-0.036304,0.007063,0.107209,0.532336,-0.746825,0.132155,0.146463,0.142366,-0.187248,0.075841,-0.522445,0.278174,-0.036553,1.000000

In [20]:
x = df.Average_Temperature.mean()
print('Average_Temperature mean value:',x)

Average_Temperature mean value: 58.46899623158616

In [21]:
x = df.Average_Wind_Direction.mean()
print('Average_Wind_Direction mean value:',x)

Average_Wind_Direction mean value: 24.95786228160329

In [22]:
x = df.Average_Wind_Speed.mean()
print('Average_Wind_Speed mean value:',x)

Average_Wind_Speed mean value: Average_Wind_Speed    10.099486
Average_Wind_Speed    10.129154
dtype: float64

In [23]:
x = df.Sky_Cover.mean()
print('Sky_Cover mean value:',x)

Sky_Cover mean value: 1.987667009249743

In [24]:
y = df.Power_Generated.unique().sum()
print('Total of Power_Generated:',y)

Total of Power_Generated: 19930889

In [25]:
df.head()

,Day_of_Year,Year,Month,Day,First_Hour_of_Period,Is_Daylight,Distance_to_Solar_Noon,Average_Temperature,Average_Wind_Direction,Average_Wind_Speed,Sky_Cover,Visibility,Relative_Humidity,Average_Wind_Speed,Average_Barometric_Pressure,Power_Generated
0,245,2008,9,1,1,False,0.859897,69,28,7.5,0,10.0,75,8.0,29.82,0
1,245,2008,9,1,4,False,0.628535,69,28,7.5,0,10.0,77,5.0,29.85,0
2,245,2008,9,1,7,True,0.397172,69,28,7.5,0,10.0,70,0.0,29.89,5418
3,245,2008,9,1,10,True,0.165810,69,28,7.5,0,10.0,33,0.0,29.91,25477
4,245,2008,9,1,13,True,0.065553,69,28,7.5,0,10.0,21,3.0,29.89,30069

In [26]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2915    False
2916    False
2917    False
2918    False
2919    False
Length: 2919, dtype: bool

In [27]:
df.duplicated().sum()

0